# Generated by Django 5.1.15 on 2026-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
